<?php

use app\Modules\tao\A0\city\Models\CityNews;
use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-inline">
                <select name="status">
                    <option value="">全部</option>
                    <option value="1">启用</option>
                    <option value="2">禁用</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">类型</label>
            <div class="layui-input-inline">
                <select name="term_id">
                    <option value="">全部</option>
                    <?php foreach (CityNews::MapKinds as $id => $t) { ?>
                        <option value="<?php echo $id ?>"><?php echo $t[1] ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal layui-btn-sm"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                重置
            </button>
        </div>
    </form>
</fieldset>

<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm" lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm"
                lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
        <button class="layui-btn layui-btn-sm layui-btn-danger"
                lay-on="batchDelete">
            <i class="fa fa-trash-o"></i>删除
        </button>

    </div>
</script>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs layui-btn-normal" lay-event="preview">预览</a>
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">删除</a>
    </div>
</script>

<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const url = '<?php echo url('tao.city/admin.news') ?>'
    admin.table.with({url})
        .render({
            toolbar: '#toolbar',
            cols: [[
                {type: 'checkbox'},
                {
                    title: '活动时间', templet: function (d) {
                        const start = admin.util.toDateString(d.dt1);
                        const end = admin.util.toDateString(d.dt2);
                        return end ? `<div>${start}<br>~ ${end}</div>` : start;
                    }, width: 120
                },
                {
                    title: '广告', width: 80, templet: function (d) {
                        return `<a lay-event="ad" class="layui-btn layui-btn-radius layui-btn-xs layui-btn-normal">${d.ad_id > 0 ? '查看' : '添加'}</a>`
                    }
                },
                {
                    field: 'title', title: '基本信息', templet: function (d) {
                        return `<div>${d.title}</div>
<div>${d.address}</div>`
                    }
                },
                {field: 'tag', title: '标签', width: 100},
                {
                    title: '图集', width: 80, templet: function (d) {
                        return d.image_ids ? `有` : '-';
                    }
                },
                {
                    title: '直播', width: 80, templet: function (d) {
                        return d.live_ids ? `有` : '-';
                    }
                },
                {
                    title: '回放', width: 80, templet: function (d) {
                        return d.video_ids ? `有` : '-';
                    }
                },
                {
                    title: '周边', width: 80, templet: function (d) {
                        return d.near_ids ? `有` : '-';
                    }
                },
                {field: 'hot', title: '热度', width: 85, text: 'edit'},
                {field: 'status', title: '状态', width: 85, templet: admin.table.switch},
                {
                    title: '操作', toolbar: '#row-action', width: 150
                }
            ]],
            lineStyle: 'height: 90px;'
        })
        .addPostSwitch()
        .addPostEditText()
        .addLayOnActions()
        .addLayEventActions({
            events: function (obj) {
                const d = obj.data;
                const prefix = '<?php echo url("tao.city/admin.news") ?>'
                switch (obj.event) {
                    case 'ad':
                        console.log('推送到广告');
                        break;
                    case 'preview':
                        admin.iframe.open(prefix + '/preview?id=' + d.id, {
                            title: '活动预览'
                        })
                        break;
                    default:
                        console.log(obj.event)
                }
            }
        });

</script>
