<?php

use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
$kind = viewData('row.kind', 0);
?>
<style>
</style>
<table class="layui-table">
    <tr>
        <td width="90">活动时间</td>
        <td>
            <?php echo date('Y-m-d', viewData('row.dt1'));
            if ($dt2 = viewData('row.dt2')) {
                echo ' - ', date('Y-m-d', $dt2);
            } ?>
        </td>
    </tr>
    <tr>
        <td>基本信息</td>
        <td>
            <div><?php echo viewData('row.title') ?></div>
            <div>【简介】<?php echo viewData('row.summary') ?></div>
            <div>【标签】<?php echo viewData('row.tag') ?></div>
            <div>【提示】<?php echo viewData('row.warning') ?></div>

        </td>
    </tr>
    <tr>
        <td>类型</td>
        <td>
            <div>【类型】<?php echo \app\Modules\tao\A0\city\Models\CityNews::getMapKind($kind)[1] ?>
                【热度】<?php echo viewData('row.hot',0) ?>
            </div>
            <?php
            $metadata = viewData('row.metadata',[]);
            switch (viewData('row.kind',0)){
                case \app\Modules\tao\A0\city\Models\CityNews::KindGame:
                    ?>
                    <div>【主队】<span><?php echo $metadata['name1'] ?></span>【球服颜色】<span><?php echo $metadata['color1'] ?></span></div>
                    <div>【客队】<span><?php echo $metadata['name2'] ?></span>【球服颜色】<span><?php echo $metadata['color2'] ?></span></div>
                    <?php
                    break;
            } ?>
        </td>
    </tr>
    <tr>
        <td>地址</td>
        <td>
            <div><?php echo viewData('row.address') ?></div>
            <div>【经度】<?php echo viewData('row.lng') ?> 【纬度】<?php echo viewData('row.lat') ?></div>
        </td>
    </tr>
    <tr>
        <td>封面</td>
        <td>
            <span>【列表图】</span>
            <img src="<?php echo viewData('row.list') ?>" style="max-height: 80px;" alt="列表图">
            <span>【横幅图】</span>
            <img src="<?php echo viewData('row.banner') ?>" style="max-height: 80px;" alt="横幅图">
        </td>
    </tr>
    <tr>
        <td>图集</td>
        <td>
            <?php foreach (viewData('row.images', []) as $item) { ?>
                <div style="margin: 0 10px 10px 0;float:left;">
                    <img style="width: 150px;" src="<?php echo $item['url'] ?>" alt="">
                    <div class="article-albums-desc ellipsis"><?php echo $item['summary'] ?></div>
                </div>
            <?php } ?>
        </td>
    </tr>
    <tr>
        <td>直播</td>
        <td>
            <?php foreach (viewData('row.lives', []) as $item) { ?>
                <div style="margin: 0 10px 10px 0;float:left;">
                    <img style="width: 150px;" src="<?php echo $item['qc'] ?>" alt="">
                    <div class="article-albums-desc ellipsis">【<?php echo $item['ptitle'] ?>】<?php echo $item['name'] ?></div>
                </div>
            <?php } ?>
        </td>
    </tr>
    <tr>
        <td>视频</td>
        <td>
            <?php foreach (viewData('row.videos', []) as $item) { ?>
                <div style="margin: 0 10px 10px 0;float: left;">
                    <img style="width: 150px;" src="<?php echo $item['cover'] ?>" alt="">
                    <div class="article-albums-desc ellipsis"><?php echo $item['title'] ?></div>
                </div>
            <?php } ?>
        </td>
    </tr>
     <tr>
        <td>周边</td>
        <td>
            <?php foreach (viewData('row.nears', []) as $item) { ?>
                <div style="margin: 0 10px 10px 0;float: left;">
                    <img style="width: 150px;" src="<?php echo $item['list'] ?>" alt="">
                    <div class="article-albums-desc ellipsis"><?php echo $item['title'] ?></div>
                </div>
            <?php } ?>
        </td>
    </tr>

</table>
