<?php

use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */

$terms = \app\Modules\tao\A0\city\Services\CityTermService::options();
$termId = viewData('api.term_id', 0);
?>
<form class="layui-form">

    <div class="layui-form-item">
        <label class="layui-form-label">球队</label>
        <div class="layui-input-inline">
            <select name="term_id">
                <option value="">请选择</option>
                <?php foreach ($terms as $id => $t) { ?>
                    <option value="<?php echo $id ?>" <?php echo $id == $termId ? 'selected' : '' ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>
        <label class="layui-form-label required">日期</label>
        <div class="layui-input-inline">
            <input name="date" type="text" class="layui-input" id="date" placeholder="yyyy-MM-dd">
        </div>
    </div>

    <?php if (!isset($_GET['id'])) { ?>
        <div class="layui-form-item">
            <label class="layui-form-label"></label>
            <div class="layui-input-block">
                <input type="checkbox" title="批量添加" lay-skin="tag" lay-filter="batch">
            </div>
        </div>
    <?php } ?>

    <div id="more" style="display: none">
        <div class="layui-form-item">
            <label class="layui-form-label">赞助商</label>
            <div class="layui-input-block">
                <textarea name="batch" class="layui-textarea"></textarea>
                <div class="layui-form-mid layui-text-em">格式：赞助商名称 金额（单位为元）。示例：AAA 200<br>多个赞助商使用换行
                </div>
            </div>
        </div>
    </div>

    <div id="one">
        <div class="layui-form-item">
            <label class="layui-form-label">名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" class="layui-input" placeholder="请输入赞助商名称"
                       value="<?php echo viewData('api.name') ?>"
                       lay-affix="clear"
                >
            </div>

            <label class="layui-form-label">金额</label>
            <div class="layui-input-inline layui-input-group">
                <input type="number" name="money" class="layui-input"
                       value="<?php echo viewData('api.money') ?>"
                       lay-affix="clear"
                >
                <div class="layui-input-split layui-input-suffix">元</div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">物品</label>
            <div class="layui-input-block">
                <input type="text" name="other" class="layui-input" placeholder="其它赞助物品"
                       value="<?php echo viewData('api.other') ?>"
                       lay-affix="clear"
                >
            </div>
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center" style="margin-top: 10px;">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php
$layui->addWindowConfig();
$layui->footer();
$date = viewData("api.date");
if ($date) {
    $date = date('Y-m-d', strtotime($date));
}
?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    })
    layui.laydate.render({
        elem: '#date', value: '<?php echo $date ?>'
    });
    const moreElem = $('#more');
    const oneElem = $('#one');
    admin.form.on('batch', function (d) {
        if (d.elem.checked) {
            oneElem.hide()
            moreElem.show();
        } else {
            oneElem.show();
            moreElem.hide();
        }
    }, 'checkbox');
</script>
