version: '3.5'

# 本机测试，使用的是本地 mysql, pgsql
# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  php:
    container_name: php
    image: authus/phalcon:5.7.0
    #image: registry.cn-shenzhen.aliyuncs.com/authus/phalcon:5.5.0
    working_dir: /var/www
    volumes:
      - ./src:/var/www:delegated
      - ./src/storage/logs:/var/log/php/:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: "serverName=docker-php"
    env_file:
      - .env

#  phpCli:
#    container_name: phpCli
#    image: authus/phalcon:5.7.0-cli
#    volumes:
#      - ./src:/var/www:delegated
#      - ./src/storage/logs:/var/log/php/:rw
#      - ./php/php.ini:/usr/local/etc/php/php.ini
#      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
#    networks:
#      - backend
#    extra_hosts:
#      - host.docker.internal:host-gateway
#    environment:
#      PHP_IDE_CONFIG: "serverName=docker-php"
#    ports:
#      - "${WS_PORT}:8282"
#    env_file:
#      - .env

#  redis:
#    container_name: redis
#    image: redis:7.2-alpine
#    environment:
#      - TZ=${TZ}
#    volumes:
#      - ${DATA_PATH_HOST}/redis:/data
#    command: "redis-server --requirepass ${REDIS_PASSWORD}"
#    privileged: true
#    ports:
#      - "${REDIS_PORT}:6379"
#    restart: always
#    networks:
#      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '${OPEN_PORT}:80'
    restart: on-failure
    volumes:
      - ./src:/var/www
      - ./nginx/location.conf:/etc/nginx/location.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx/:rw
    networks:
      - backend
    links:
      - php