<?php
use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<form class="layui-form">

    <div class="layui-form-item">
        <label class="layui-form-label">登录密码</label>
        <div class="layui-input-block">
            <input type="password" name="password" class="layui-input"
                   lay-verify="required"
                   lay-reqtext="请填写登录密码"
                   required placeholder="请输入登录密码" value="">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">确认密码</label>
        <div class="layui-input-block">
            <input type="password" name="password_confirm" class="layui-input"
                   lay-verify="required"
                   lay-reqtext="请再次填写登录密码"
                   required placeholder="请再次输入登录密码" value="">
        </div>
    </div>

    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>

<?php $layui->footer(); ?>
<script>
    admin.form.submitFirst(function (data) {
        admin.iframe.closeFromParent(true)
    })
</script>
