<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;
use App\Modules\tao\sdk\phaxui\Layui\LayuiHtml;
use App\Modules\tao\A0\cms\Models\CmsCategory;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */

\App\Modules\tao\A0\cms\Helper\CmsHtmlHelper::header();
//dd(viewData());
?>

<form class="layui-form">

    <div style="display: flex;flex-direction: row;">
        <div class="layui-form-item" style="width: 300px;margin-right: 10px;">

            <?php \App\Modules\tao\sdk\phaxui\Layui\LayuiHtml::upload('封面', 'cover', [
                'value' => viewData('api.cover'), 'tip' => '建议尺寸 620 * 300'
            ]); ?>
        </div>
        <div style="flex: 1;">
            <div class="layui-form-item">
                <label class="layui-form-label required">标题</label>
                <div class="layui-input-inline">
                    <input type="text" class="layui-input" name="title"
                           value="<?php echo viewData('api.title') ?>"
                           lay-verify="required" lay-reqtext="请填写图集名称"
                           placeholder="请填写图集名称"
                    >
                </div>

                <label class="layui-form-label">标签</label>
                <div class="layui-input-inline">
                    <input type="text" class="layui-input" name="tag"
                           value="<?php echo viewData('api.tag') ?>"
                           placeholder="通常用于分组使用"
                    >
                </div>
                <div class="layui-form-mid layui-text-em">多个标签使用空格分割</div>
            </div>

            <div class="layui-form-item">
                <label class="layui-form-label">简介</label>
                <div class="layui-input-block">
                    <input type="text" name="summary" class="layui-input" placeholder="请填写简介"
                           value="<?php echo viewData('api.summary') ?>">
                </div>
            </div>
        </div>

    </div>
    <?php \App\Modules\tao\A0\cms\Helper\CmsHtmlHelper::ImageHtml(); ?>


    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php

$layui->addWindowConfig([]);
$layui->footer();

$items = viewData('api.images');
\App\Modules\tao\A0\cms\Helper\CmsHtmlHelper::ImageJs($items);
?>

<script>
    // 提交事件
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    }, data => {
        data['image_ids'] = vmImage.data.items.map(d => d.id).join(',');
        return data;
    })
    admin.upload.run();
</script>


