<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-inline">
                <select name="status">
                    <option value="">全部</option>
                    <option value="1">启用</option>
                    <option value="2">禁用</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">TAG</label>
            <div class="layui-input-inline">
                <input name="tag" placeholder="" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary">
                重置
            </button>
        </div>
    </form>
</fieldset>

<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm" lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm"
                lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
        <button class="layui-btn layui-btn-sm layui-btn-danger"
                lay-on="batchDelete">
            <i class="fa fa-trash-o"></i>删除
        </button>

    </div>
</script>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs layui-btn-normal" lay-event="preview">预览</a>
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">删除</a>
    </div>
</script>

<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao.cms/admin.album") ?>';
    admin.table.with({url: prefix})
        .render({
            toolbar: '#toolbar',
            cols: [[
                {type: 'checkbox'},
                {field: 'id', title: 'ID', width: 50},
                {field: 'created_at', title: '创建时间', width: 120, templet: admin.table.humanTime},
                {field: 'sort', title: '排序', width: 100, align: 'center', edit: 'text'},
                {field: 'tag', title: 'TAG', width: 150, align: 'center', edit: 'text'},
                {field: 'cover', title: '封面', width: 70, templet: admin.table.image},
                {
                    title: '图集', templet: function (d) {
                        return `<div>
<div>${d.title}</div>
<div>${d.summary}</div>
</div>`;
                    }
                },

                {field: 'status', title: '状态', width: 85, templet: admin.table.switch},
                {
                    title: '操作', toolbar: '#row-action', width: 140,
                }
            ]],
            lineStyle: '60px'
        })
        .addPostSwitch()
        .addPostEditText()
        .addLayOnActions()
        .addLayEventActions({
            events: function (obj) {
                if ('preview' == obj.event) {
                    const d = obj.data;
                    admin.iframe.open("<?php echo url('tao.cms/admin.album/preview') ?>?id=" + d.id, {
                        title: '图集预览',
                        full: true,
                    })
                }

            }
        });
</script>
