<?php
use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */

?>
<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">TAG</label>
        <div class="layui-input-inline">
            <input type="number" name="tag" class="layui-input" placeholder="分组 TAG" value="<?php echo viewData('api.tag',0) ?>">
        </div>

        <label class="layui-form-label">排序</label>
        <div class="layui-input-inline">
            <input type="number" name="sort" class="layui-input" placeholder="排序" value="<?php echo viewData('api.sort',0) ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label required">链接标题</label>
        <div class="layui-input-inline">
            <input type="text" name="title" class="layui-input" placeholder="请输入链接标题"
                   lay-verify="required" lay-reqtext="请输入链接标题"
                   value="<?php echo viewData('api.title') ?>">
        </div>

        <label class="layui-form-label required">链接地址</label>
        <div class="layui-input-inline">
            <input type="text" name="href" class="layui-input" placeholder="请输入链接地址"
                   lay-verify="required" lay-reqtext="请输入链接地址"
                   value="<?php echo viewData('api.href') ?>">
        </div>
    </div>

    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>
<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    })
</script>
