<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;
use App\Modules\tao\A0\open\Data\Config;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
//dd(viewData());
?>
<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">应用名称</label>
        <div class="layui-input-inline">
            <input type="text" name="title" class="layui-input"
                   placeholder="请输入应用名称"
                   lay-verify="required" lay-reqtext="请输入应用名称"
                   value="<?php echo viewData('api.title') ?>">
        </div>
        <?php $platform = viewData('api.platform', 0) ?>
        <label class="layui-form-label required">平台</label>
        <div class="layui-input-inline">
            <select class="layui-select" name="platform">
                <?php foreach (Config::MapPlatform as $v => $t) { ?>
                    <option value="<?php echo $v ?>" <?php echo viewDataCompare($platform, 'selected', $v, true) ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>

        <?php $kind = viewData('api.kind', 'mini'); ?>
        <label class="layui-form-label required">应用类型</label>
        <div class="layui-input-inline">
            <select class="layui-select" name="kind">
                <?php foreach (Config::MapKinds as $v => $t) { ?>
                    <option value="<?php echo $v ?>" <?php echo viewDataCompare($kind, 'selected', $v, true) ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>

    </div>

    <div class="layui-form-item">
        <label class="layui-form-label required">Appid</label>
        <div class="layui-input-inline">
            <input type="text" name="appid" class="layui-input"
                   placeholder="请输入 Appid"
                   lay-verify="required"
                   value="<?php echo viewData('api.appid') ?>">
        </div>

        <label class="layui-form-label required">Secret</label>
        <div class="layui-input-inline">
            <input type="text" name="secret" class="layui-input"
                   placeholder="请输入 Secret"
                   lay-verify="required"
                   value="<?php echo viewData('api.secret') ?>">
        </div>

    </div>
    <!-- 微信 -->
    <div>
        <div class="layui-form-item">
            <label class="layui-form-label">CropId</label>
            <div class="layui-input-inline">
                <input type="text" name="crop_id" class="layui-input" placeholder="企业微信 cropId"
                       value="<?php echo viewData('api.crop_id') ?>">
            </div>
            <label class="layui-form-label">Token</label>
            <div class="layui-input-inline">
                <input type="text" name="token" class="layui-input" placeholder="token"
                       value="<?php echo viewData('api.token') ?>">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">EncMethod</label>
            <div class="layui-input-inline">
                <input type="text" name="enc_method" class="layui-input" placeholder="加密方式"
                       value="<?php echo viewData('api.enc_method') ?>">
            </div>
            <label class="layui-form-label">AesKey</label>
            <div class="layui-input-inline">
                <input type="text" name="aes_key" class="layui-input" placeholder="消息加密密钥"
                       value="<?php echo viewData('api.aes_key') ?>">
            </div>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">沙盒</label>
        <div class="layui-input-inline">
            <input type="checkbox" name="sandbox" title="是" <?php echo viewDataCompare('api.sandbox', 'checked') ?>>
        </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" class="layui-input" placeholder=""
                   value="<?php echo viewData('api.remark') ?>">
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    }, function (data) {
        return Object.assign(data, {})
    })
</script>
