<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>


<fieldset class="table-search-fieldset layui-hide" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">平台</label>
            <div class="layui-input-inline">
                <select name="platform">
                    <option value="">全部</option>
                    <?php foreach (\App\Modules\tao\A0\open\Data\Config::MapPlatform as $v => $t) { ?>
                        <option value="<?php echo $v ?>"><?php echo $t ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-inline">
                <select name="status">
                    <option value="">全部</option>
                    <option value="1">启用</option>
                    <option value="2">禁用</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <div class="layui-form-item layui-inline">
                <a class="layui-btn layui-btn-normal layui-btn-sm"
                   lay-submit>搜索</a>
                <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                    重置
                </button>
            </div>
    </form>
</fieldset>
<div style="margin: 5px 0;">抖音平台公钥/应用公钥/应用私钥为交易系统专用；<a
            href="https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/server/signature-algorithm"
            target="_blank">【查看文档】</a></div>
<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm" lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm"
                lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
    </div>
</script>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">删除</a>
    </div>
</script>

<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao.open/admin.app") ?>';
    const certURL = '<?php echo url("tao.open/admin.app/cert", true) ?>';
    const mapKeyTitle = {
        public_key: '平台公钥',
        rsa_public_key: '应用公钥',
        rsa_private_key: '应用私钥'
    };
    const mapKind = <?php echo json_encode(\App\Modules\tao\A0\open\Data\Config::MapKinds)?>;
    const mapPlatform = <?php echo json_encode(\App\Modules\tao\A0\open\Data\Config::MapPlatform) ?>

        admin.table.with({url: prefix})
            .render({
                toolbar: '#toolbar',
                cols: [[
                    // {type: 'checkbox'},
                    // {field: 'id', title: 'ID', width: 50},
                    // {field: 'created_at', title: '创建时间', width: 120, templet: admin.table.humanTime},

                    {
                        title: '平台/类型', width: 120, templet: function (d) {
                            return mapPlatform[d.platform] + mapKind[d.kind];
                        }
                    },
                    {field: 'status', title: '状态', width: 85, templet: admin.table.switch},
                    {field: 'online', title: '线上', width: 85, templet: admin.table.switch},
                    {field: 'sandbox', title: '沙盒', width: 85, templet: admin.table.switch},
                    {
                        field: 'appid', title: '应用名称/appid', width: 250, templet: function (d) {
                            return `<div>${d.title}</div><div>${d.appid}</div>` + (d.platform == 1 && d.kind == 'work' ? `<div>cropID: ${d.crop_id}</div>` : '');
                        }
                    },
                    {
                        title: '交易证书', width: 250, templet: function (d) {
                            return `<div>平台公钥: ${d.public_key ? '已上传' : '未上传'}
<div class="group-radio" style="display: inline-block;">
<button type="button" class="layui-btn upload_btn layui-btn-xs"
    lay-options="{accept: 'file',data:{id:${d.id},name:'public_key'}}">
上传
</button>
<button type="button" class="layui-btn layui-btn-xs"
lay-on='inputBtn' data-info='{"id":${d.id},"name":"public_key"}'>
输入
</button>
` + (d.public_key ? `<button type="button" class="layui-btn layui-btn-xs layui-btn-warm"
lay-on='discardBtn' data-info='{"id":${d.id},"name":"public_key"}'>取消</button>` : '') + `</div></div>` + `<div>应用公钥: ${d.rsa_public_key ? '已上传' : '未上传'}
<div class="group-radio" style="display: inline-block;">
<button type="button" class="layui-btn upload_btn layui-btn-xs"
    lay-options="{accept: 'file',data:{id:${d.id},name:'rsa_public_key'}}">
上传
</button>
<button type="button" class="layui-btn layui-btn-xs"
    lay-on='inputBtn' data-info='{"id":${d.id},"name":"rsa_public_key"}'>
输入
</button>
` + (d.rsa_public_key ? `<button type="button" class="layui-btn layui-btn-xs layui-btn-warm"
lay-on='discardBtn' data-info='{"id":${d.id},"name":"rsa_public_key"}'>取消</button>` : '') + `</div></div>` + `<div>应用私钥: ${d.rsa_private_key ? '已上传' : '未上传'}
<div class="group-radio" style="display: inline-block;">
<button type="button" class="layui-btn upload_btn layui-btn-xs"
    lay-options="{accept: 'file',data:{id:${d.id},name:'rsa_private_key'}}">
上传
</button>
<button type="button" class="layui-btn layui-btn-xs"
    lay-on='inputBtn' data-info='{"id":${d.id},"name":"rsa_private_key"}'>
输入
</button>
` + (d.rsa_private_key ? `<button type="button" class="layui-btn layui-btn-xs layui-btn-warm"
lay-on='discardBtn' data-info='{"id":${d.id},"name":"rsa_private_key"}'>取消</button>` : '') + `</div></div>`;
                        }
                    },
                    // {field: 'sort', title: '排序', width: 70, edit: 'text'},

                    {field: 'remark', title: '备注'},
                    {
                        title: '操作', width: 130, toolbar: '#row-action'
                    }
                ]],
                lineStyle: '60px',
                done: function (res, curr, count) { // 表格加载后，对上传按钮进行渲染
                    const tableId = this.id;
                    const tableElem = this.elem;
                    const tableViewElem = tableElem.next();

                    layui.upload.render({
                        elem: tableViewElem.find('.upload_btn'),
                        url: certURL,
                        accept: 'file',
                        done: function (res) {
                            layer.closeAll('loading'); //关闭loading
                            layer.msg('上传成功');
                            admin.table.reloadData();
                        },
                        error: function (index, upload) {
                            layer.closeAll('loading'); //关闭loading
                            layer.msg('上传失败，请重试');
                        }
                    });

                    layui.util.on({
                        inputBtn: function () {
                            const postData = JSON.parse($(this).attr('data-info'));
                            const title = mapKeyTitle[postData.name];

                            layer.prompt({
                                title: '请输入' + title + '内容',
                                formType: 2,
                                maxlength: 2000
                            }, function (value, index, elem) {
                                layer.close(index);

                                if (value === '') {
                                    return elem.focus();
                                } else {
                                    postData.value = value;
                                    admin.ajax.post({
                                        url: certURL, data: postData,
                                    }, function () {
                                        admin.table.reloadData();
                                    })
                                }
                            });
                        },
                        discardBtn: function () {
                            const postData = JSON.parse($(this).attr('data-info'));
                            const title = mapKeyTitle[postData.title];
                            admin.layer.confirm('确定要移除' + title + '吗？', function () {
                                postData.value = '';
                                admin.ajax.post({
                                    url: certURL, data: postData
                                });
                            })
                        }
                    })
                },
            })
            .addPostSwitch(['online', 'status', 'sandbox'])
            .addPostEditText()
            .addLayOnActions()
            .addLayEventActions();

    function discardCert(id, name, title) {
    }
</script>
