<?php
use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>
    <form class="layui-form">


        <div class="layui-form-item">
            <label class="layui-form-label required">中文标题</label>
            <div class="layui-input-inline">
                <input type="text" name="title" class="layui-input" placeholder="请输入中文标题"
                       lay-verify="required" lay-reqtext="请输入中文标题"
                       value="<?php echo viewData('api.title') ?>">
            </div>

            <label class="layui-form-label required">英文名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" class="layui-input" placeholder="请输入英文名称"
                       lay-verify="required" lay-reqtext="请输入英文名称"
                       value="<?php echo viewData('api.name') ?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label required">标签</label>
            <div class="layui-input-inline">
                <input type="text" name="tag" class="layui-input" placeholder="标签"
                       lay-verify="required" lay-reqtext="标签名称"
                       value="<?php echo viewData('api.tag') ?>">
            </div>

            <label class="layui-form-label">排序</label>
            <div class="layui-input-inline">
                <input type="number" name="sort" placeholder="请输入菜单排序" value="<?php echo viewData('api.sort',0) ?>"
                       class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">内容</label>
            <div class="layui-input-block">
                <textarea name="content" class="layui-textarea" placeholder="请输入单页内容" id="content"><?php echo viewData('api.content') ?></textarea>
            </div>
        </div>

        <div class="hr-line"></div>
        <div class="layui-form-item text-center">
            <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
        </div>

    </form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

    <script>
        admin.form.submitFirst(() => {
            admin.iframe.closeFromParent(true);
        }, function (data) {
            return Object.assign(data, {content: tinymce.activeEditor.getContent()})
        })
    </script>
<?php
\App\Modules\tao\sdk\phaxui\TinyMce::init();
?>