<?php
use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>
<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">账号类型</label>
        <div class="layui-input-inline">
            <select class="layui-select" name="kind">
                <?php foreach (\app\Modules\tao\A0\wechat\Models\WechatApp::MapKinds as $v => $t) { ?>
                    <option value="<?php echo $v ?>"
                        <?php echo viewDataCompare('row.kind', 'selected', $v) ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>
        <label class="layui-form-label required">中文标题</label>
        <div class="layui-input-inline">
            <input type="text" name="title" class="layui-input" placeholder="请输入标题"
                   lay-verify="required" lay-reqtext="请输入中文标题"
                   value="<?php echo viewData('row.title') ?>">
        </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label required">AppId</label>
        <div class="layui-input-inline">
            <input type="text" name="app_id" class="layui-input" placeholder="appId"
                   lay-verify="required" lay-reqtext="请输入 appId"
                   value="<?php echo viewData('row.app_id') ?>">
        </div>
        <label class="layui-form-label required">AppSecret</label>
        <div class="layui-input-inline">
            <input type="text" name="secret" class="layui-input" placeholder="应用密钥 appSecret"
                   lylay-verify="required" lay-reqtext="请输入 AppSecret"
                   value="<?php echo viewData('row.secret') ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">CropId</label>
        <div class="layui-input-inline">
            <input type="text" name="crop_id" class="layui-input" placeholder="企业微信 cropId"
                   value="<?php echo viewData('row.crop_id') ?>">
        </div>
        <label class="layui-form-label">Token</label>
        <div class="layui-input-inline">
            <input type="text" name="token" class="layui-input" placeholder="token"
                   value="<?php echo viewData('row.token') ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">EncMethod</label>
        <div class="layui-input-inline">
            <input type="text" name="enc_method" class="layui-input" placeholder="加密方式"
                   value="<?php echo viewData('row.enc_method') ?>">
        </div>
        <label class="layui-form-label">AesKey</label>
        <div class="layui-input-inline">
            <input type="text" name="aes_key" class="layui-input" placeholder="消息加密密钥"
                   value="<?php echo viewData('row.aes_key') ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" class="layui-input" placeholder=""
                   value="<?php echo viewData('row.remark') ?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">排序</label>
        <div class="layui-input-inline">
            <input type="number" name="sort" class="layui-input"
                   value="<?php echo viewData('row.sort', 0) ?>">
        </div>

    </div>

    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    }, function (data) {
        return Object.assign(data, {})
    })
</script>
