<?php

use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */

?>
<form class="layui-form" id="form">

    <div class="layui-form-item">
        <div class="layui-inline">
            <label class="layui-form-label">开始时间</label>
            <div class="layui-input-inline">
                <input type="text" name="begin_at"
                       class="layui-input" id="begin_at" placeholder="yyyy-MM-dd HH:mm:ss">
            </div>
            <div class="layui-form-mid layui-text-em">不填写则表示立即生效</div>
        </div>
        <div class="layui-inline">
            <label class="layui-form-label">结束时间</label>
            <div class="layui-input-inline">
                <input type="text" name="end_at"
                       class="layui-input" id="end_at" placeholder="yyyy-MM-dd HH:mm:ss">
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-inline">
            <label class="layui-form-label">排序</label>
            <div class="layui-input-inline">
                <input type="number" name="sort"
                       class="layui-input" value="<?php echo viewData('row.sort', 0) ?>">
            </div>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">位置</label>
        <div class="layui-input-block" style="width: 440px;display: inline-block;float: left;margin-left: 0;">
            <?php foreach (['at_banner' => '横幅', 'at_index' => '首页', 'at_list' => '列表页', 'at_page' => '详情页'] as $name => $title) { ?>
                <input type="checkbox" name="<?php echo $name ?>" title="<?php echo $title ?>"
                       lay-skin="tag" <?php echo viewDataCompare('row.' . $name, 'checked') ?>>
            <?php } ?>
        </div>

        <label class="layui-form-label">标识</label>
        <div class="layui-input-inline">
            <input type="text" name="tag" placeholder="自定义标识" class="layui-input"
                   value="<?php echo viewData('row.tag', '') ?>">
        </div>
        <div class="layui-form-mid layui-text-em">通常用于分组</div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">标识</label>
        <div class="layui-input-block">
            <?php foreach (['live' => '直播', 'ad' => 'AD'] as $name => $title) { ?>
                <input type="checkbox" name="<?php echo $name ?>" title="<?php echo $title ?>"
                       lay-skin="tag" <?php echo viewDataCompare('row.' . $name, 'checked') ?>>
            <?php } ?>
        </div>
    </div>
    <div class="layui-form-item">
        <?php \app\Modules\tao\sdk\phaxui\Layui\LayuiHtml::upload('封面', 'cover', [
            'value' => viewData('row.cover'),
            'tip' => '广告图片建议尺寸 640 * 60'
        ]); ?>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label required">标题</label>
        <div class="layui-input-block">
            <input type="text" name="title" class="layui-input" placeholder="请输入广告标题"
                   lay-affix="clear" maxlength="255"
                   value="<?php echo viewData('row.title') ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label required">地址</label>
        <div class="layui-input-block">
            <input type="text" name="link" class="layui-input" placeholder="请输入链接地址或内部路径"
                   lay-affix="clear" maxlength="255"
                   value="<?php echo viewData('row.link') ?>">
            <div class="layui-form-mid">
                <a class="layui-btn layui-btn-sm">单页选择</a>
                <a class="layui-btn layui-btn-sm">文章选择</a>
                <a class="layui-btn layui-btn-sm">图集选择</a>
            </div>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" class="layui-input" placeholder="备注内容仅内部可见"
                   lay-affix="clear" maxlength="255"
                   value="<?php echo viewData('row.remark') ?>">
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php
$layui->addWindowConfig();
$layui->footer();
?>
<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    })
    admin.upload.run()

    laydate.render({
        elem: '#begin_at',
        type: 'datetime',
        value: '<?php echo viewData("row.begin_at") ?>'
    });
    laydate.render({
        elem: '#end_at',
        type: 'datetime',
        value: '<?php echo viewData("row.end_at") ?>'
    });
</script>
