<?php
/**
 * @var \App\Modules\tao\sdk\phaxui\Layui\Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 * @var \App\Modules\tao\Models\SystemUser $user 当前用户的信息
 * @var bool $demo 是否为演示信息
 */
//dd(__FILE__,viewData());

$indexWelcome = url(\App\Modules\tao\Config\Config::IndexWelcome);
$menuTree = viewData('api.menuTree',[]);
//dd($menuTree);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $pageTitle ?? config('app.name') ?></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php $layui->header(); ?>
    <?php \App\Modules\tao\sdk\phaxui\HtmlAssets::addViewFile('tao.css'); ?>
    <style>
        <?php include_once __DIR__.'/admin.css'?>

        .layadmin-side-shrink .layui-logo {
            background-image: url(<?php echo config('app.logo') ?>)
        }

        .layui-logo {
            border-bottom: 1px solid grey;
        }

        .layui-side-menu .layui-nav > .layui-nav-item i.fa {
            position: absolute;
            top: 50%;
            left: 20px;
            margin-top: -8px
        }
    </style>
</head>
<body class="layui-layout-body" id="LAY_home_iframe">
<div id="LAY_app">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <!-- 头部区域 -->
            <ul class="layui-nav layui-layout-left">
                <li class="layui-nav-item layadmin-flexible" lay-unselect>
                    <a href="javascript:;" lay-on="flexible" title="侧边伸缩">
                        <i class="layui-icon layui-icon-shrink-right" id="LAY_app_flexible"></i>
                    </a>
                </li>
                <?php
                foreach ($menuTree as $index => $menu) { ?>
                    <li class="switchSidebar layui-nav-item layui-hide-xs <?php echo $index == 0 ? 'layui-this' : '' ?>"
                        lay-on="switchSidebar" data-id="<?php echo $menu['id'] ?>"
                        id="switchSidebar-<?php echo $menu['id'] ?>"
                    >
                        <a href="javascript:;"><?php echo $menu['title'] ?></a>
                    </li>
                <?php } ?>
            </ul>
            <ul class="layui-nav layui-layout-right">

                <!-- 暂未实现 -->
                <li class="layui-nav-item layui-hide" lay-on="message" lay-unselect>
                    <a href="javascript:;" title="消息中心">
                        <i class="layui-icon layui-icon-notice"></i>

                        <!-- 如果有新消息，则显示小圆点 -->
                        <span class="layui-badge-dot"></span>
                    </a>
                </li>

                <li class="layui-nav-item layui-hide-xs">
                    <a href="/" target="_blank">
                        站点首页
                    </a>
                </li>

                <li class="layui-nav-item layui-hide-xs" lay-on="refresh" lay-unselect>
                    <a href="javascript:;" title="刷新页面">
                        <i class="fa fa-refresh"></i>
                    </a>
                </li>
                <li class="layui-nav-item layui-hide-xs" lay-on="clear" lay-unselect>
                    <a href="javascript:;" title="清理缓存">
                        <i class="fa fa-trash-o"></i>
                    </a>
                </li>
                <li class="layui-nav-item" lay-unselect>
                    <a href="javascript:;">
                        <?php if ($user->head_img) { ?>
                            <img src="<?php echo $user->head_img ?>"
                                 class="layui-nav-img" width="50" height="50">
                        <?php } else { ?>
                            <i class="layui-icon layui-icon-face-smile"></i>
                        <?php } ?>
                        <?php $nickname = \Phax\Utils\MyData::firstValue([
                            $user->nickname,
                            \Phax\Utils\MyData::subtext($user->phone, 3),
                            \Phax\Utils\MyData::subtext($user->email, 3)
                        ], in_array($user->id, \App\Modules\tao\Config\Config::superAdminIds()) ? '管理员' : '会员');
                        ?>
                        <cite><?php echo $nickname ?></cite>
                    </a>
                    <dl class="layui-nav-child" style="text-align: center;">
                        <dd><a lay-href="<?php echo url('tao/user.index/index') ?>"
                               data-tips="基本資料">基本资料 <span
                                        class="layui-badge-dot"></span></a></dd>
                        <dd><a lay-href="<?php echo url('tao/user.index/password') ?>"
                               data-tips="修改密碼">修改密码</a></dd>
                        <hr>
                        <dd lay-on="logout" style="text-align: center;"><a href="javascript:;">退出</a></dd>
                    </dl>
                </li>

                <li class="layui-nav-item" lay-unselect lay-header-event="menuRight">
                    <a href="javascript:;"><i class="layui-icon layui-icon-more-vertical"></i></a>
                </li>
            </ul>
        </div>

        <!-- 侧边菜单 -->
        <div class="layui-side layui-side-menu">
            <div class="layui-side-scroll">
                <div class="layui-logo" lay-href="<?php echo url('tao') ?>">
                    <span><?php echo config('app.name') ?></span>
                </div>
                <!-- 显示模块菜单 -->
                <div id="menuTree">
                    <?php foreach ($menuTree as $index => $firstMenus) { ?>
                        <ul id="layui-nav-<?php echo $firstMenus['id'] ?>"
                            class="layui-nav layui-nav-tree <?php echo $index > 0 ? 'layui-hide' : '' ?>"
                        >
                            <?php if (isset($firstMenus['child'])) {
                                foreach ($firstMenus['child'] as $secondMenus) {
                                    $hasSecondMenuChild = isset($secondMenus['child']) && count($secondMenus['child']) > 0;
                                    ?>
                                    <li class="layui-nav-item" id="layui-nav-item-<?php echo $secondMenus['id'] ?>">
                                        <a <?php echo $hasSecondMenuChild ? 'href="javascript:;"' : 'lay-href="' . $secondMenus['href'] . '"' ?>
                                                data-tips="<?php echo $secondMenus['title'] ?>"
                                                data-id="<?php echo $secondMenus['id'] ?>"
                                        >
                                            <i class="<?php echo $secondMenus['icon'] ?>"></i>
                                            <cite><?php echo $secondMenus['title'] ?></cite>
                                        </a>

                                        <?php
// 二级菜单
                                        if ($hasSecondMenuChild) { ?>
                                            <dl class="layui-nav-child" style="padding-left: 20px;">
                                                <?php foreach ($secondMenus['child'] as $thirdMenus) { ?>
                                                    <dd  id="layui-nav-item-<?php echo $thirdMenus['id'] ?>">
                                                        <a lay-href="<?php echo $thirdMenus['href'] ?>"
                                                           data-tips="<?php echo $thirdMenus['title'] ?>"
                                                           data-id="<?php echo $secondMenus['id'],'-', $thirdMenus['id'] ?>"
                                                        >
                                                            <i class="<?php echo $thirdMenus['icon'] ?>"></i>
                                                            <cite><?php echo $thirdMenus['title'] ?></cite>
                                                        </a>
                                                    </dd>
                                                <?php } ?>
                                            </dl>
                                        <?php } ?>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </div>
            </div>
        </div>

        <!-- 页面标签 -->
        <div class="layadmin-pagetabs" id="LAY_app_tabs">
            <div class="layui-icon layadmin-tabs-control layui-icon-prev" layadmin-event="leftPage"></div>
            <div class="layui-icon layadmin-tabs-control layui-icon-next" layadmin-event="rightPage"></div>
            <div class="layui-icon layadmin-tabs-control layui-icon-down">
                <ul class="layui-nav layadmin-tabs-select" lay-filter="layadmin-pagetabs-nav">
                    <li class="layui-nav-item" lay-unselect>
                        <a href="javascript:;"></a>
                        <dl class="layui-nav-child layui-anim-fadein">
                            <dd layadmin-event="closeThisTabs"><a href="javascript:;">关闭当前标签页</a></dd>
                            <dd layadmin-event="closeOtherTabs"><a href="javascript:;">关闭其它标签页</a></dd>
                            <dd layadmin-event="closeAllTabs"><a href="javascript:;">关闭全部标签页</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
            <div class="layui-tab" lay-unauto lay-allowClose="true" lay-filter="layadmin-layout-tabs">
                <ul class="layui-tab-title" id="LAY_app_tabsheader">
                    <!-- 默认首页 -->
                    <li lay-id="<?php echo $indexWelcome ?>"
                        onclick="tabs.append('<?php echo $indexWelcome ?>')"
                        class="layui-this">
                        <i class="layui-icon layui-icon-home"></i>
                    </li>
                </ul>
            </div>
        </div>


        <!-- 主体内容 -->
        <div class="layui-body" id="LAY_app_body">
            <!---->
            <div class="layadmin-tabsbody-item layui-show">
                <iframe src="<?php echo $indexWelcome ?>"
                        frameborder="0" class="layadmin-iframe"></iframe>
            </div>
        </div>

        <!-- 辅助元素，一般用于移动设备下遮罩 -->
        <div class="layadmin-body-shade" layadmin-event="shade"></div>
    </div>
</div>

</body>
<?php $layui->addWindowConfig([]); ?>
<?php $layui->footer(); ?>

<script><?php include_once __DIR__ . '/index.js' ?></script>
<script>
    admin.util.layOn({
        message: function () {
            admin.layer.success('TODO 消息中心')
        },
        clear: function () {
            admin.ajax.get({
                url: '<?php echo url("tao/user.index/clear", true) ?>'
            })
        },
        logout: function () {
            admin.ajax.get({
                url: '<?php echo url("tao/user.index/logout", true) ?>'
            }, function (rst) {
                admin.cache.clear();
                setTimeout(function () {
                    location.href = rst.data || '/';
                }, 1000)
            })
        }
    })
</script>
</html>