<?php
/**
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 * @var string $msg 错误提示信息
 * @var string $url 点击 “确定” 按钮后跳转的网址
 */

use App\Modules\tao\sdk\phaxui\HtmlAssets;

HtmlAssets::initWithCdn();
$layui = \App\Modules\tao\sdk\phaxui\Layui\Layui::getInstance();
$title = $title ?? '错误';
// 1 正确, 2 错误(X), 3 询问，4 锁定, 5 不开心, 6 开心(笑脸) 7 感叹号
$icon = $icon ?? 2;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title ?></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php $layui->header(); ?>
</head>
<body>
</body>
<?php $layui->footer(); ?>
<script>
    const _redirect = encodeURIComponent(location.href);
    <?php if (empty($url)){?>
    layui.layer.alert('<?php echo $msg ?>', {icon: <?php echo $icon ?>}, function (index) {
        layer.close(index);
        history.back();
    });
    <?php } else {?>
    const _href = '<?php echo $url ?>';
    layui.layer.confirm('<?php echo $msg ?>',
        {
            icon: <?php echo $icon ?>,
            title: '<?php echo $title ?>'
        },
        function (index) {
            layer.close(index)
            if (_href === 'close') {
                admin.cache.remove('tabs') // 移除当前 tabs
            } else {
                location.href = _href.includes('?')
                    ? _href + '&_redirect=' + _redirect
                    : _href + '?_redirect=' + _redirect;
            }
        }, function (index) {
            layer.close(index);
            history.back();
        })
    <?php } ?>
</script>
</html>


