<?php
/**
 * @var $this \Phalcon\Mvc\View\Engine\AbstractEngine
 */

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Phalcon Demo</title>
</head>
<body>
<h1>Demo Module Main Layout - 导航</h1>
<ul>
    <li><a href="/">返回首页</a></li>
    <li><a href="/m/demo/index/hello">/m/demo/index/hello</a></li>
    <li><a href="/m/demo/index/hello/phax">/m/demo/index/hello/phax</a> 参数</li>
    <li><a href="/m/demo/todo/list">/m/demo/todo/list</a> todo 控制器</li>
    <li><a href="/m/demo/db.test/hello">/m/demo/db.test/hello</a> 子目录</li>
</ul>

<h5>子模块 - Database</h5>
<ul>
    <li><a href="/m/demo.db/test">/m/demo/db.demo</a> 联表查询</li>
    <li><a href="/m/demo.db/test/insert">/m/demo/db.test/insert</a> 添加记录(时间戳)</li>
    <li><a href="/m/demo.db/test/get">/m/demo/db.test/get</a> 记录查询(修改器)</li>
    <li><a href="/m/demo.db/test/remove">/m/demo/db.test/remove</a> 删除记录(软删除)</li>
    <li><a href="/m/demo.db/test/list">/m/demo/db.test/list</a> 列表查询</li>
    <li><a href="/m/demo.db/test/form">/m/demo/db.test/form</a> 表单 Form</li>
    <li><a href="/m/demo.db/user.info/name">/m/demo.db/user.info/name</a> 子模块+子目录</li>
</ul>

<div> ~~~~~ </div>
<?php echo $this->getContent() ?>
<div> ~~~~~ </div>
</body>
</html>