<form class="layui-form">
    <h3 class="mb10">Mock</h3>

    <div class="hint layui-form-mid">
        启用假性发送后，所有短信/邮件发送平台将被停用。需要您自己进入后台查看发送的短信/邮件验证码；此功能通常用在程序开发阶段。
    </div>
    <div>
        <div class="layui-form-item">
            <label class="layui-form-label">是否启用</label>
            <div class="layui-input-block">
                <?php foreach ([0 => '禁用', 1 => '启用'] as $v => $t) { ?>
                    <input type="radio" name="sms_mock" value="<?php echo $v ?>"
                           title="<?php echo $t ?>" <?php systemConfigCompare('sms.sms_mock', 'checked', $v); ?>>
                <?php } ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">发送结果</label>
            <div class="layui-input-block">
                <input type="radio" name="sms_mock_result" value="0" title="随机结果"
                    <?php systemConfigCompare('sms.sms_mock_result', 'checked', 0) ?>
                >
                <input type="radio" name="sms_mock_result" value="1" title="发送成功"
                    <?php systemConfigCompare('sms.sms_mock_result', 'checked', '1') ?>
                >
                <input type="radio" name="sms_mock_result" value="2" title="发送失败"
                    <?php systemConfigCompare('sms.sms_mock_result', 'checked', 2) ?>
                >

            </div>
        </div>
    </div>

    <h3 class="mb10">阿里云</h3>

    <div class="layui-form-item">
        <label class="layui-form-label">Key</label>
        <div class="layui-input-inline">
            <input type="text" name="alisms_access_key" class="layui-input"
                   placeholder="阿里 AccessKey ID"
                   value="<?php echo systemConfig('sms.alisms_access_key') ?>">
        </div>

        <label class="layui-form-label">Secret</label>
        <div class="layui-input-inline">
            <input type="text" name="alisms_access_secret" class="layui-input"
                   placeholder="阿里 AccessKey Secret"
                   value="<?php echo systemConfig('sms.alisms_access_secret') ?>">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">发送短信</label>
        <div class="layui-input-block">
            <?php foreach ([0 => '禁用', 1 => '启用'] as $v => $t) { ?>
                <input type="radio" name="alisms" value="<?php echo $v ?>"
                       title="<?php echo $t ?>" <?php systemConfigCompare('sms.alisms', 'checked', $v); ?>>
            <?php } ?>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">短信签名</label>
        <div class="layui-input-inline">
            <input type="text" name="alisms_signname" class="layui-input"
                   placeholder="阿里短信签名"
                   value="<?php echo systemConfig('sms.alisms_signname') ?>">
        </div>

        <label class="layui-form-label">短信条数</label>
        <div class="layui-input-inline">
            <input type="text" name="alisms_num" class="layui-input"
                   placeholder="阿里短信条数"
                   value="<?php echo systemConfig('sms.alisms_num') ?>">
        </div>
        <div class="hint layui-form-mid">当条数为0时，将会停用当前平台短信发送功能</div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">发送邮件</label>
        <div class="layui-input-block">
            <?php foreach ([0 => '禁用', 1 => '启用'] as $v => $t) { ?>
                <input type="radio" name="aliemail" value="<?php echo $v ?>"
                       title="<?php echo $t ?>" <?php systemConfigCompare('sms.aliemail', 'checked', $v); ?>>
            <?php } ?>
        </div>
    </div>

    <div class="layui-form-item">

        <label class="layui-form-label">发件人</label>
        <div class="layui-input-inline">
            <input type="text" name="aliemail_fromalias" class="layui-input"
                   placeholder="邮件发件人名称"
                   value="<?php echo systemConfig('sms.aliemail_fromalias') ?>">
        </div>
        <label class="layui-form-label">发送账号</label>
        <div class="layui-input-inline">
            <input type="text" name="aliemail_account" class="layui-input"
                   placeholder="邮件发送账号"
                   value="<?php echo systemConfig('sms.aliemail_account') ?>">
        </div>
    </div>

    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm"
                lay-submit
                lay-filter="submit_sms">确认
        </button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<script>
    admin.form.onSubmit('submit_sms', function (data) {
        admin.ajax.post({
            url: prefix + '/save/sms', data
        })
    })
</script>