<?php

use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<form class="layui-form" lay-filter="near">

    <div class="layui-form-item">
    <label class="layui-form-label">名称</label>
    <div class="layui-input-block">
        <div class="layui-form-mid layui-text-em"><?php echo viewData('api.title') ?></div>
    </div>
    </div>
    <?php \app\Modules\tao\A0\city\Helper\CityHtmlHelper::addressHtml(); ?>

    <div class="hr-line"></div>
    <div class="layui-form-item text-center" style="margin-top: 10px;">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit
                lay-filter="demo1">确认
        </button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>

<?php
$layui->addWindowConfig();
$layui->footer();
?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    })
</script>
<?php \app\Modules\tao\A0\city\Helper\CityHtmlHelper::addressJs(); ?>
