<?php

use app\Modules\tao\A0\city\Models\CityNear;
use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
$kind = viewData('api.kind', 0);
?>
    <style>
    </style>
    <table class="layui-table">
        <tr>
            <td width="90">创建时间</td>
            <td><?php echo date('Y-m-d', viewData('api.created_at')) ?></td>
        </tr>
        <tr>
            <td>基本信息</td>
            <td>
                <div><?php echo viewData('api.title') ?></div>
                <div>类型: 【<?php echo CityNear::getMapKind($kind)[1] ?>】；
                    置顶: 【<?php echo viewData('api.top') ? '是' : '否' ?>】；
                    热门: 【<?php echo viewData('api.hot') ? '是' : '否' ?>】
                </div>
                <div>标签: <?php echo viewData('api.tag') ?></div>
                <div>简介: <?php echo viewData('api.summary') ?></div>
            </td>
        </tr>
        <tr>
            <td>地址</td>
            <td>
                <div><?php echo viewData('api.address') ?></div>
                <div>经度:【<?php echo viewData('api.lng') ?>】 纬度:【<?php echo viewData('api.lat') ?>】</div>
            </td>
        </tr>
        <tr>
            <td>封面</td>
            <td>
                <span>列表图</span>
                <img src="<?php echo viewData('api.list') ?>" style="max-height: 80px;" alt="列表图">
                <span>横幅图</span>
                <img src="<?php echo viewData('api.banner') ?>" style="max-height: 80px;" alt="横幅图">
            </td>
        </tr>
        <tr>
            <td>图集</td>
            <td>
                <?php foreach (viewData('api.images', []) as $item) { ?>
                    <div style="margin: 0 10px 10px 0;float:left;">
                        <img style="width: 150px;" src="<?php echo $item['url'] ?>" alt="">
                        <div class="article-albums-desc ellipsis"><?php echo $item['summary'] ?></div>
                    </div>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td>视频</td>
            <td>
                <?php foreach (viewData('api.videos', []) as $item) { ?>
                    <div style="margin: 0 10px 10px 0;float: left;">
                        <img style="width: 150px;" src="<?php echo $item['cover'] ?>" alt="">
                        <div class="article-albums-desc ellipsis"><?php echo $item['title'] ?></div>
                    </div>
                <?php } ?>
            </td>
        </tr>
    </table>
<?php
$layui->addWindowConfig();
$layui->footer();

?>