<?php
use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset layui-hide" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">

        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal  layui-btn-sm"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary  layui-btn-sm">
                重置
            </button>
        </div>
    </form>
</fieldset>


<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm"
                lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm"
                lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
        <button class="layui-btn layui-btn-sm layui-btn-danger"
                lay-on="batchDelete">
            <i class="fa fa-trash-o"></i>删除
        </button>
    </div>
</script>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">
            删除</a>
    </div>
</script>
<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao/user.quick") ?>';
    admin.table.with({url: prefix,})
        .render({
            toolbar: '#toolbar',
            cols: [[
                {type: "checkbox"},
                {field: 'id', width: 80, title: 'ID'},
                {field: 'sort', width: 80, title: '排序', edit: 'text'},
                {field: 'icon', width: 80, title: '图标', templet: admin.table.icon},
                {field: 'title', width: 150, title: '菜单名称', edit: 'text'},
                {field: 'href', minWidth: 120, title: '链接地址', edit: 'text'},
                {field: 'remark', minWidth: 80, title: '备注信息', edit: 'text'},
                {field: 'status', title: '状态', width: 85, templet: admin.table.switch},
                {field: 'created_at', width: 150, title: '创建时间'},
                {width: 200, title: '操作', toolbar: '#row-action'}
            ]]
        })
        .addPostSwitch()
        .addPostEditText()
        .addLayOnActions()
        .addLayEventActions({
            url: prefix,
            events: function (obj) {
                console.log(obj.event, obj.data);
            }
        })
</script>