<?php

use app\Modules\tao\sdk\phaxui\Layui\Layui;
use app\Modules\tao\sdk\phaxui\Layui\LayuiHtml;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */

$terms = \app\Modules\tao\A0\city\Services\CityTermService::options();
$termId = viewData('row.term_id', 0);
?>
<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">球队</label>
        <div class="layui-input-inline">
            <select name="term_id">
                <option value="">请选择</option>
                <?php foreach ($terms as $id => $t) { ?>
                    <option value="<?php echo $id ?>" <?php echo $id == $termId ? 'selected' : '' ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>
    </div>


    <?php LayuiHtml::upload('头像', 'avatar', [
        'value' => viewData('row.avatar')]); ?>

    <div class="layui-form-item">
        <label class="layui-form-label required">名称</label>
        <div class="layui-input-inline">
            <input type="text" name="name" class="layui-input" placeholder="请输入球员名称"
                   value="<?php echo viewData('row.name') ?>"
                   lay-affix="clear"
                   lay-verify="required" lay-reqtext="输入球员名称"
            >
        </div>

        <label class="layui-form-label">号码</label>
        <div class="layui-input-inline">
            <input type="text" name="code" class="layui-input"
                   value="<?php echo viewData('row.code') ?>"
                   lay-affix="clear"
            >
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">性别</label>
        <div class="layui-input-block">
            <?php
            $sex = viewData('row.sex', 1);
            foreach ([1 => '男', 2 => '女'] as $v => $t) {
                ?>
                <input type="radio" name="sex" value="<?php echo $v ?>"
                       title="<?php echo $t ?>" <?php echo $v == $sex ? 'checked' : '' ?>>
            <?php } ?>
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center" style="margin-top: 10px;">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    }, function (data) {
        return Object.assign(data, {})
    })

    admin.upload.run();
</script>
