<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-inline">
                <select name="status">
                    <option value="">全部</option>
                    <option value="1">启用</option>
                    <option value="2">禁用</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <input type="checkbox" name="active" title="展示中的广告">
        </div>

        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">开始时间</label>
            <div class="layui-input-inline">
                <input type="text" name="begin_at"
                       class="layui-input" id="begin_at" placeholder="yyyy-MM-dd HH:mm:ss">
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">TAG</label>
            <div class="layui-input-inline">
                <input name="tag" placeholder="" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary">
                重置
            </button>
        </div>
    </form>
</fieldset>

<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm" lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm"
                lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
        <button class="layui-btn layui-btn-sm layui-btn-danger"
                lay-on="batchDelete">
            <i class="fa fa-trash-o"></i>删除
        </button>

    </div>
</script>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">删除</a>
    </div>
</script>

<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao.cms/admin.ad") ?>';
    admin.table.with({url: prefix})
        .render({
            toolbar: '#toolbar',
            cols: [[
                {type: 'checkbox'},
                {
                    title: '时间', width: 200, templet: function (v) {
                        return `
<div>创建: <span>${admin.table.humanTime(v.created_at)}</span></div>
<div>上线: <span>${admin.table.humanTime(v.begin_at)}</span></div>
<div>下线: <span>${admin.table.humanTime(v.end_at)}</span></div>
`
                    }
                },

                {field: 'gname', title: '组名', width: 80, align: 'center', edit: 'text'},
                {field: 'tag', title: 'TAG', width: 80, align: 'center', edit: 'text'},
                {field: 'sort', title: '排序', width: 60, align: 'center', edit: 'text'},
                {field: 'title', title: '广告', width: 150,templet:function (d){
                    return `<div>
${admin.table.image(d.cover,true)}
</div><div>${d.title}</div>`;
                    }},

                {field: 'status', title: '状态', width: 80, templet: admin.table.switch},
                {field: 'at_banner', title: '横幅', width: 80, templet: admin.table.switch},
                {field: 'at_index', title: '首页', width: 80, templet: admin.table.switch},
                {field: 'at_list', title: '列表页', width: 80, templet: admin.table.switch},
                {field: 'at_page', title: '详情页', width: 80, templet: admin.table.switch},
                {field: 'remark', title: '备注'},
                {
                    title: '操作', toolbar: '#row-action', width: 140,
                }
            ]],
            lineStyle: '60px'
        })
        .addPostSwitch(['status', 'at_index', 'at_list', 'at_page'])
        .addPostEditText()
        .addLayOnActions()
        .addLayEventActions();
    laydate.render({
        elem: '#begin_at',
        type: 'datetime',
        value: '<?php echo viewData("api.begin_at") ?>'
    });
</script>
