
<?php
use app\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>
<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">应用名称</label>
        <div class="layui-input-inline">
            <input type="text" name="title" class="layui-input"
                   placeholder="请输入应用名称"
                   lay-verify="required" lay-reqtext="请输入应用名称"
                   value="<?php echo viewData('row.title') ?>">
        </div>
        <?php $kind = viewData('row.kind', 'mini') ?>
        <label class="layui-form-label required">应用类型</label>
        <div class="layui-input-inline">
            <select class="layui-select" name="kind">
                <?php foreach (\app\Modules\tao\A0\tiktok\Models\TiktokApp::MapKinds as $v => $t) { ?>
                    <option value="<?php echo $v ?>" <?php echo viewDataCompare('row.kind', 'selected', $kind) ?>><?php echo $t ?></option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label required">AppID</label>
        <div class="layui-input-inline">
            <input type="text" name="appid" class="layui-input"
                   placeholder="请输入 AppID"
                   lay-verify="required"
                   value="<?php echo viewData('row.appid') ?>">
        </div>

        <label class="layui-form-label required">Secret</label>
        <div class="layui-input-inline">
            <input type="text" name="secret" class="layui-input"
                   placeholder="请输入 Secret"
                   lay-verify="required"
                   value="<?php echo viewData('row.secret') ?>">
        </div>

    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">沙盒</label>
        <div class="layui-input-inline">
            <input type="checkbox" name="sandbox" title="是" <?php echo viewDataCompare('row.sandbox', 'checked') ?>>
        </div>
    </div>


    <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" class="layui-input" placeholder=""
                   value="<?php echo viewData('row.remark') ?>">
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

<script>
    admin.form.submitFirst(() => {
        admin.iframe.closeFromParent(true);
    }, function (data) {
        return Object.assign(data, {})
    })
</script>
