<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;
use App\Modules\tao\sdk\phaxui\Layui\LayuiHtml;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>
<form class="layui-form" action="" method="post" lay-filter="form">


    <div class="layui-form-item">
        <label class="layui-form-label"></label>
        <div class="layui-input-block">
            <img src="<?php echo viewData('api.url') ?>" alt="图片地址" style="width: 150px;">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">描述</label>
        <div class="layui-input-block">
            <textarea name="summary" class="layui-textarea" placeholder="图片描述内容"
                      maxlength="255"><?php echo viewData('api.summary') ?></textarea>
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit lay-filter="demo1">确认
        </button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<?php $layui->addWindowConfig(); ?>
<?php $layui->footer(); ?>

<script>
    admin.form.submitFirst(function (data) {
        const res = admin.util.pick(data.data, 'id', 'summary', 'url')
        admin.storage.save('images', res);
        admin.iframe.closeFromParent(true);
    })

    admin.upload.run()
</script>
