<?php
/**
 * @var \App\Modules\tao\sdk\phaxui\Layui\Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
\App\Modules\tao\sdk\phaxui\HtmlAssets::addHeaderFile(__DIR__ . '/auth.css');
?>


<form class="layui-form">
    <div class="auth-container">
        <h2 style="margin-bottom: 15px;">重置密码</h2>
        <div class="layui-form-item">
            <div class="layui-input-wrap">
                <div class="layui-input-prefix">
                    <i class="layui-icon layui-icon-password"></i>
                </div>
                <input type="password" name="password" value=""
                       lay-verify="required" lay-reqtext="请填写密码"
                       placeholder="密码"
                       autocomplete="off" class="layui-input" id="reg-password" lay-affix="eye">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-wrap">
                <div class="layui-input-prefix">
                    <i class="layui-icon layui-icon-password"></i>
                </div>
                <input type="password" name="confirmPassword" value=""
                       lay-verify="required|confirmPassword" lay-reqtext="请再次输入密码"
                       placeholder="确认密码" autocomplete="off" class="layui-input" lay-affix="eye">
            </div>
        </div>


        <div class="layui-form-item link">
            <a href="javascript:;" class="layui-btn layui-btn-fluid"
               id="submit"
               lay-submit lay-filter="demo-password">重置密码
            </a>
        </div>
    </div>
</form>

<?php $layui->footer(); ?>
<script>
    // 自定义验证规则
    form.verify({
        // 确认密码
        confirmPassword: function (value, item) {
            const passwordValue = $('#reg-password').val();
            if (value !== passwordValue) {
                return '两次密码输入不一致';
            }
        }
    });

    // 提交事件
    form.on('submit(demo-password)', function (data) {
        const field = data.field; // 获取表单字段值

        admin.ajax.post({
            url: '<?php echo url('tao/auth/password', true) ?>',
            data: {
                password: field.password,
            },
        }, function () {
            $('#submit').addClass('layui-btn-disabled');
            admin.layer.alert('已重置密码成功，请往登录', function () {
                window.location.href = '<?php echo url("tao/auth/index") ?>'
            }, {title: '成功'})
        })

        return false;
    });
</script>
