<?php
/**
 * @var \App\Modules\tao\sdk\phaxui\Layui\Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset layui-hide" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">

        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">注册时间</label>
            <div class="layui-input-inline">
                <input name="created_at" value="" id="created_at"
                       placeholder="请输入注册时间" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal layui-btn-sm"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">
                重置
            </button>
        </div>
    </form>
</fieldset>

<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm"
                lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm" lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>
    </div>
</script>

<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-success layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="password">设置密码</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="delete">删除</a>
    </div>
</script>

<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao/admin.user", false) ?>';
    const mapBinds = <?php echo json_encode(\App\Modules\tao\Config\Data::MapBinds) ?>;
    admin.table.with({
        url: prefix,
    })
        .render({
            toolbar: '#toolbar',

            cols: [[
                // {type: 'checkbox'},
                // {field: 'id', title: 'ID', width: 50},
                {
                    title: '基本信息', templet: function (d) {
                        return `<div class="flex-rows">
<div style="width: 35px;"><img src="${d.head_img}" class="full-width" /></div>
<div class="flex-1" style="padding-left: 10px;">${d.nickname}</div>
</div>`
                    }
                },
                {
                    title: '手机/邮箱', templet: function (d) {
                        return (d.phone ? '<span>' + d.phone + (d['phone_valid'] ? '<span>[已验证]</span>' : '[否]') + '</span>' : '')
                            + (d.email ? '<span>' + d.email + (d['email_valid'] ? '<span>[已验证]</span>' : '[否]') + '</span>' : '')
                    }, width: 250
                },
                {
                    width: 130, title: '来源', templet: function (d) {
                        if (d.binds) {
                            return d.binds.map(bind => {
                                return `<div>${mapBinds[bind]}</div>`
                            })
                        } else {
                            return '';
                        }
                    }
                }, {
                    width: 130, title: '角色', templet: function (d) {
                        return d.roles.map(role => {
                            return `${role.title}`;
                        }).join('<br/>')
                    }
                },
                {field: 'status', title: '状态', width: 85, templet: admin.table.switch},
                {field: 'created_at', width: 120, title: '创建时间', templet: admin.table.humanTime},
                {
                    title: '操作', width: 200, toolbar: '#row-action'
                }
            ]],
            lineStyle: 'height: 80px;',
        })
        .addPostSwitch()
        .addLayOnActions().addLayEventActions({
        events: function (obj) {
            switch (obj.event) {
                case 'password':
                    const id = obj.data.id;
                    admin.iframe.open(prefix + '/password?id=' + id, {title: '设置密码'})
                    break;
            }
        }
    });

    admin.date.renderDate('created_at')

</script>
