<?php
/**
 * @var \App\Modules\tao\sdk\phaxui\Layui\Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<form class="layui-form">

    <div class="layui-form-item">
        <label class="layui-form-label">旧的密码</label>
        <div class="layui-input-inline">
            <input type="password" name="old_password" class="layui-input" placeholder="请输入登录密码" value="">
        </div>
        <div class="layui-form-mid layui-text-em">填写原登录密码，首次设置密码可为空</div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label required">新的密码</label>
        <div class="layui-input-inline">
            <input type="password" name="password" class="layui-input"
                   placeholder="请输入您的新密码" value=""
                   lay-verify="required"
                   lay-reqtext="请输入新密码"
            >
        </div>
        <div class="layui-form-mid layui-text-em">填写输入您的新密码，密码到至少6位</div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label required">确认密码</label>
        <div class="layui-input-inline">
            <input type="password" name="password_again" class="layui-input"
                   placeholder="请再次输入您的新密码" value=""
                   lay-verify="required"
                   lay-reqtext="请输入确认密码"
            >
        </div>
        <div class="layui-form-mid layui-text-em">填写再次登录密码</div>
    </div>

    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm" lay-submit>确认</button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>
</form>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    admin.form.submitFirst(function () {
        admin.iframe.closeFromParent();
    })
</script>
