<div class="layui-form-item">
    <label class="layui-form-label required">地址</label>
    <div class="layui-input-block">
        <input type="text" name="address" class="layui-input" placeholder="请输入地址"
               lay-affix="clear"
               lay-verify="required" lay-reqtext="必须填写地址"
               value="<?php echo viewData('row.address') ?>"
        >
    </div>
</div>
<div class="hint my-1" style="margin-left: 65px;margin-bottom: 15px;">填写经纬度信息有利于用户进行地图定位; 坐标拾取工具
    <?php foreach ([
                       '百度' => 'https://api.map.baidu.com/lbsapi/getpoint/index.html',
                   ] as $text => $href) { ?>
        <a class="layui-btn-xs layui-btn layui-btn-normal layui-btn-radius" href="<?php echo $href ?>" target="_blank"><i c class="layui-icon layui-icon-website"></i><?php echo $text ?></a>
    <?php } ?>;
    <input type="text" placeholder="将坐标点复制到这里" id="pointText">
    <a class="layui-btn layui-btn-xs" lay-on="splitPointText">拆分坐标</a>
</div>
<div class="layui-form-item">
    <label class="layui-form-label">经度</label>
    <div class="layui-input-inline">
        <input type="number" name="lng" class="layui-input" placeholder=""
               lay-affix="clear"
               value="<?php echo viewData('row.lng') ?>"
        >
    </div>
    <div class="layui-form-mid layui-text-em">LNG -180~180 度</div>
    <label class="layui-form-label">纬度</label>
    <div class="layui-input-inline">
        <input type="number" name="lat" class="layui-input" placeholder=""
               lay-affix="clear"
               value="<?php echo viewData('row.lat') ?>"
        >
    </div>
    <div class="layui-form-mid layui-text-em">LAT -90~90 度</div>
</div>