; add extra config here

; static 和 动态属性会被警告
; https://github.com/phalcon/cphalcon/issues/16408
; https://github.com/php/php-src/blob/master/php.ini-production
; 当前 example 默认为 product 环境，注释提示为本地开发环境配置

; E_ALL & ~E_DEPRECATED
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
; On
display_errors="Off"
; On
display_startup_errors="Off"
log_errors="On"
error_log=/var/log/php/php_errors.log
memory_limit=512M
session.save_path="/tmp"

zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.jit_debug=1
opcache.jit=1255
opcache.jit_buffer_size=100M

;https://www.jetbrains.com/help/idea/configuring-xdebug.html#configuring-xdebug-docker
; xdebug default is close, only open it in your local development env. follow the commands to open it
; cd /usr/local/etc/php/conf.d/
; mv docker-php-ext-xdebug.ini.disabled docker-php-ext-xdebug.ini
; restart the php service

; 本地开发时可开启
;[xdebug]
;xdebug.mode=debug,develop
;xdebug.discover_client_host=0
;xdebug.idekey=XDEBUG_SESSION_START
;xdebug.client_port = 19003
;xdebug.client_host=host.docker.internal
;xdebug.start_with_request=yes


