<?php
/**
 * @var $this \Phalcon\Mvc\View\Engine\AbstractEngine
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo config('app.name') ?> - phalcon admin</title>
</head>
<body>

<div>路由功能扩展 src/tao996/phalcon/phax/src/phax/Foundation/RouterTest.php 文件</div>

<h1>view/index.phtml 布局文件 - 导航</h1>
<h4>单应用（没有单独子模块功能）</h4>
<ul>
    <li><a href="/">首页</a></li>
    <li><a href="/index/about">/index/about</a></li>
    <li><a href="/index/about/phax/5">/index/about/phax/5</a> 带参数</li>
    <li></li>
    <li><a href="/sub.test/abc">/sub.test/abc</a> 子目录</li>
    <li><a href="/sub/sub1.me/say">/sub/sub1.me/say</a> 子模块+子目录</li>
</ul>
<h5>多模块</h5>
<ul>
    <li><a href="/m/demo">/m/demo</a> => /m/demo/index/index</li>
</ul>
<h6>~~~~~ start ~~~</h6>
<?php echo $this->getContent() ?>
<h6>~~~~~ end ~~~~~</h6>
</body>
</html>

