<?php

use app\Modules\tao\BaseResponseController;
use app\Modules\tao\sdk\phaxui\HtmlAssets;

/**
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
$layui = app\Modules\tao\sdk\phaxui\Layui\Layui::getInstance();
?>
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title><?php echo $title ?? '' ?></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://lf3-cdn-tos.bytegoofy.com/obj/goofy/developer/jssdk/jssdk-1.2.1.js"></script>
    <?php
    $layui->header();
    HtmlAssets::outputHeaders();
    $layui->footer();
    \app\Modules\tao\sdk\phaxui\HtmlAssets::outputFooters();
    ?>
</head>
<body>
<div>
    <?php echo $this->view->getContent(); ?>
</div>
</body>

<?php
\app\Modules\tao\sdk\phaxui\HtmlAssets::appendTemplateJs(BaseResponseController::$theme);
?>

</html>