<?php

use App\Modules\tao\sdk\phaxui\Layui\Layui;

/**
 * @var Layui $layui
 * @var \Phalcon\Mvc\View\Engine\AbstractEngine $this
 */
?>

<fieldset class="table-search-fieldset" id="table-search">
    <legend>条件搜索</legend>
    <form class="layui-form layui-form-pane form-search" lay-filter="form-search">

        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">存储位置</label>
            <div class="layui-input-inline">
                <select name="upload_type" class="layui-select">
                    <option value="">全部</option>
                    <option value="local">本地</option>
                    <option value="alioss">阿里云</option>
                    <option value="qnoss">七牛云</option>
                    <option value="txcos">腾讯云</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">关键字</label>
            <div class="layui-input-inline">
                <input name="summary" value=""
                       placeholder="文件名/标记/备注"
                       class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-inline">
            <label class="layui-form-label">创建时间</label>
            <div class="layui-input-inline">
                <input name="created_at" id="created_at"
                       value="" placeholder="请输入创建时间" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-inline">
            <a class="layui-btn layui-btn-normal"
               lay-submit>搜索</a>
            <button type="reset" class="layui-btn layui-btn-primary">
                重置
            </button>
        </div>
    </form>
</fieldset>
<script type="text/html" id="row-action">
    <div class="layui-btn-container">
        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove">删除</a>
    </div>
</script>
<script type="text/html" id="toolbar">
    <div class="layui-table-tool-temp">
        <button class="layui-btn layui-btn-sm"
                lay-on="refresh">
            <i class="fa fa-refresh"></i>
        </button>

        <button class="layui-btn layui-btn-normal layui-btn-sm" lay-on="create">
            <i class="fa fa-plus"></i>添加
        </button>

        <button class="layui-btn layui-btn-sm layui-btn-danger"
                lay-on="batchDelete">
            <i class="fa fa-trash-o"></i>删除
        </button>
    </div>
</script>
<table id="table" class="layui-hide"></table>

<?php $layui->footer(); ?>
<?php $layui->addWindowConfig([]); ?>
<script>
    const prefix = '<?php echo url("tao/user.uploadfile") ?>';
    const ss = {
        local: '本地', alioss: '阿里云', qnoss: '七牛云', txcos: '腾讯云'
    };
    admin.date.renderDate('created_at')

    admin.table.with({url: prefix})
        .render({
            toolbar: '#toolbar',
            cols: [[
                {type: "checkbox"},
                // {field: 'id', width: 80, title: 'ID', search: false},
                {field: 'created_at', width: 120, title: '上传时间', templet: admin.table.humanTime},
                {
                    field: 'upload_type',
                    width: 100,
                    title: '存储位置',
                    templet: function (d) {
                        return ss[d.upload_type] || '---'
                    },
                },
                {
                    field: 'url', width: 70, search: false, title: '图片',
                    templet: admin.table.image
                },
                {
                    field: 'summary', title: '文件名/标记/备注', edit: 'text',
                },
                {
                    width: 100, title: '图片大小', templet: function (d) {
                        if (d.file_size > 0) {
                            return Math.round(d.file_size / 1000) + ' kb';
                        } else {
                            return '-';
                        }
                    }, search: false
                },
                {
                    width: 100, title: '图片尺寸', templet: function (d) {
                        if (d.width > 0) {
                            return d.width + ' * ' + d.height;
                        } else {
                            return '-';
                        }
                    }
                },

                {title: '操作', width: 120, toolbar: '#row-action'}
            ]],
            lineStyle: 'height: 60px;'
        })
        .addPostEditText()
        .addLayEventActions()
        .addLayOnActions();

    layui.util.on('lay-on', {
        showUrl: function () {
            const u = $(this).attr('title');
            layui.layer.alert(u);
        }
    })
</script>
