<form class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label required">存储方式</label>
        <div class="layui-input-block">
            <div>
                <?php foreach ([
                                   'def' => '系统默认',
                                   'local' => '本地存储',
                                   'qnoss' => '七牛云oss',
                                   'alioss' => '阿里云oss',
                                   'txcos' => '腾讯云cos'
                               ] as $key => $val) { ?>
                    <input type="radio" name="upload_type" lay-filter="upload_type"
                           value="<?php echo $key ?>"
                           title="<?php echo $val ?>"
                        <?php systemConfigCompare('upload.upload_type', 'checked', $key) ?>
                    >
                <?php } ?>
            </div>
            <!--            <div class="hint">默认情况下，上传文件保存在本地 /upload/yymmdd/ 目录下</div>-->
        </div>
    </div>
    <h3 class="mb10">基本设置</h3>
    <div class="layui-form-item">
        <label class="layui-form-label required">允许类型</label>
        <div class="layui-input-block">
            <input type="text" name="upload_allow_ext" class="layui-input"
                   lay-verify="required"
                   lay-reqtext="请输入允许类型"
                   placeholder="请输入允许类型"
                   lay-affix="clear"
                   value="<?php echo systemConfig('upload.upload_allow_ext') ?>">
            <div class="hint">服务端允许上传的文件类型，使用英文逗号做分隔符</div>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">允许大小</label>
        <div class="layui-input-inline">
            <input type="number" name="upload_allow_size" class="layui-input"
                   lay-affix="clear"
                   value="<?php echo systemConfig('upload.upload_allow_size') ?>">
        </div>
        <div class="layui-form-mid layui-text-em">单位 mb，默认为 5</div>
    </div>

    <h3 class="mb10"><input type="checkbox" name="oss_frontend" class="layui-input" value="1"
            <?php systemConfigCompare('upload.oss_frontend', 'checked'); ?>
                            title="Web 端直传"
        ></h3>
    <div class="layui-form-item">
        <label class="layui-form-label">存储目录</label>
        <div class="layui-input-inline">
            <input type="text" name="oss_dir" class="layui-input"
                   placeholder="文件在云上存储的子目录"
                   lay-affix="clear"
                   value="<?php echo systemConfig('upload.oss_dir') ?>">
        </div>
        <div class="layui-form-mid layui-text-em">存储子目录</div>
        <label class="layui-form-label">文件类型</label>
        <div class="layui-input-inline">
            <input type="text" name="oss_mimeLimit" class="layui-input"
                   placeholder="允许的文件类型"
                   value="<?php echo systemConfig('upload.oss_mimeLimit') ?>">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">文件大小</label>
        <div class="layui-input-inline">
            <input type="number" name="sso_size" class="layui-input"
                   lay-affix="clear"
                   value="<?php echo systemConfig('upload.oss_size') ?>">
        </div>
        <div class="layui-form-mid layui-text-em">单位 mb，默认为 5</div>

        <label class="layui-form-label">有效期</label>
        <div class="layui-input-inline">
            <input type="number" name="alioss_seconds" class="layui-input"
                   placeholder="有效期(秒)"
                   lay-affix="clear"
                   value="<?php echo systemConfig('upload.oss_seconds') ?>">
        </div>
        <div class="layui-form-mid layui-text-em">默认为 3600 秒</div>
    </div>

    <div>
        <h3 class="mb10">七牛云</h3>
        <div class="layui-form-item">
            <label class="layui-form-label">公钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="qnoss_access_key" class="layui-input"
                       placeholder="请输入 AccessKey"
                       value="<?php echo systemConfig('upload.qnoss_access_key') ?>">
            </div>

            <label class="layui-form-label">私钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="qnoss_secret_key" class="layui-input"
                       placeholder="请输入 SecretKey"
                       value="<?php echo systemConfig('upload.qnoss_secret_key') ?>">

            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">存储空间 Bucket</label>
            <div class="layui-input-inline">
                <input type="text" name="qnoss_bucket" class="layui-input"
                       placeholder="请输入存储桶地域"
                       value="<?php echo systemConfig('upload.qnoss_bucket') ?>">
            </div>

            <label class="layui-form-label">访问域名 Domain</label>
            <div class="layui-input-inline">
                <input type="text" name="qnoss_domain" class="layui-input"
                       placeholder="请输入访问域名"
                       value="<?php echo systemConfig('upload.qnoss_domain') ?>">
            </div>
        </div>

    </div>

    <div>
        <h3 class="mb10">阿里云</h3>
        <div class="layui-form-item">
            <label class="layui-form-label">公钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="alioss_access_key_id" class="layui-input"
                       placeholder="请输入公钥信息"
                       value="<?php echo systemConfig('upload.alioss_access_key_id') ?>">
            </div>

            <label class="layui-form-label">私钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="alioss_access_key_secret" class="layui-input"
                       placeholder="请输入私钥信息"
                       value="<?php echo systemConfig('upload.alioss_access_key_secret') ?>">
            </div>

            <label class="layui-form-label">空间名称</label>
            <div class="layui-input-inline">
                <input type="text" name="alioss_bucket" class="layui-input"
                       placeholder="请输入空间名称"
                       value="<?php echo systemConfig('upload.alioss_bucket') ?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">数据中心</label>
            <div class="layui-input-inline">
                <input type="text" name="alioss_endpoint" class="layui-input"
                       placeholder="请输入数据中心"
                       value="<?php echo systemConfig('upload.alioss_endpoint') ?>">
            </div>
            <div class="hint">例子：https://oss-cn-shenzhen.aliyuncs.com</div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">访问域名</label>
            <div class="layui-input-inline">
                <input type="text" name="alioss_domain" class="layui-input"
                       placeholder="请输入访问域名"
                       value="<?php echo systemConfig('upload.alioss_domain') ?>">
            </div>
            <div class="hint">例子：phax.oss-cn-shenzhen.aliyuncs.com</div>
        </div>
    </div>

    <div>
        <h3 class="mb10">腾讯云</h3>
        <div class="layui-form-item">
            <label class="layui-form-label">公钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="txcos_secret_id" class="layui-input"
                       placeholder="请输入公钥信息"
                       value="<?php echo systemConfig('upload.txcos_secret_id') ?>">
            </div>

            <label class="layui-form-label">私钥信息</label>
            <div class="layui-input-inline">
                <input type="text" name="txcos_secret_key" class="layui-input"
                       placeholder="请输入私钥信息"
                       value="<?php echo systemConfig('upload.txcos_secret_key') ?>">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">存储桶地域</label>
            <div class="layui-input-inline">
                <input type="text" name="txcos_region" class="layui-input"
                       placeholder="请输入存储桶地域"
                       value="<?php echo systemConfig('upload.txcos_region') ?>">
            </div>

            <label class="layui-form-label">存储桶名称</label>
            <div class="layui-input-inline">
                <input type="text" name="txcos_bucket" class="layui-input"
                       placeholder="请输入存储桶名称"
                       value="<?php echo systemConfig('upload.txcos_bucket') ?>">
            </div>
        </div>
    </div>


    <div class="hr-line"></div>
    <div class="layui-form-item text-center">
        <button type="submit" class="layui-btn layui-btn-normal layui-btn-sm"
                lay-filter="submit_upload"
                lay-submit>确认
        </button>
        <button type="reset" class="layui-btn layui-btn-primary layui-btn-sm">重置</button>
    </div>

</form>
<script>
    admin.form.onSubmit('submit_upload', function (data) {
        admin.ajax.post({
            url: prefix + '/save/upload', data
        })
    })
    admin.form.on('upload_type', function (data) {
        const v = data.elem.value;
        // console.log(v);
    }, 'radio')
</script>